#WAP to enter 7 fruits in a list entered by user
print("Enter fruit 1\n")
a = input()
print("Enter fruit 2\n")
b = input()
print("Enter fruit 3\n")
c = input()
print("Enter fruit 4\n")
d = input()
print("Enter fruit 5\n")
e = input()
print("Enter fruit 6\n")
f = input()
print("Enter fruit 7\n")
g = input()
fruits = [a,b,c,d,e,f,g]
print(fruits)
